# Generated by Django 3.2.7 on 2021-09-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('meal', models.CharField(choices=[('DM1', 'Dummy Meal 1'), ('DM2', 'Dummy Meal 2'), ('DM3', 'Dummy Meal 3'), ('DM4', 'Dummy Meal 4'), ('DM5', 'Dummy Meal 5')], max_length=4)),
                ('mid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('meal', models.CharField(choices=[('DM11', 'Dummy Meal 11'), ('DM12', 'Dummy Meal 12'), ('DM13', 'Dummy Meal 13'), ('DM14', 'Dummy Meal 14'), ('DM15', 'Dummy Meal 15')], max_length=4)),
                ('mid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('meal', models.CharField(choices=[('DM6', 'Dummy Meal 6'), ('DM7', 'Dummy Meal 7'), ('DM8', 'Dummy Meal 8'), ('DM9', 'Dummy Meal 9'), ('DM10', 'Dummy Meal 10')], max_length=4)),
                ('mid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('hostel', models.CharField(choices=[('A', 'Abuja'), ('N', 'Naraguta'), ('P', 'PG'), ('Z', 'Zion')], default='N', max_length=1)),
                ('block', models.CharField(max_length=20)),
                ('room_no', models.IntegerField(max_length=10)),
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.breakfast')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dinner')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lunch')),
            ],
        ),
    ]
