# Generated by Django 3.2.7 on 2021-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
